# Generated by Django 2.1.5 on 2019-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='Detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['detail'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('business_name', models.CharField(max_length=100, unique=True, verbose_name='Apellidos y Nombres: Razón Social')),
                ('tradename', models.CharField(blank=True, max_length=60, verbose_name='nombre comercial')),
                ('main_address', models.TextField(max_length=200, verbose_name='Dirección Matriz')),
                ('special_contributor', models.CharField(blank=True, max_length=10, verbose_name='contribuyente Especial')),
                ('forced_to_keep_accounting', models.BooleanField(default=False, verbose_name='obligado a llevar contabilidad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuration/logo/', verbose_name='Logotipo')),
                ('type_of_enviroment', models.IntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCION')], default=1)),
                ('token_to_sign', models.IntegerField(choices=[(1, 'ANF - Certificado Exportado'), (2, 'ANF - Plug & Sing'), (3, 'BCE - ikey2032'), (4, 'BCE - Aladin eToken Pro'), (5, 'SD - ePass3030 auto'), (6, 'SD - BioPass3000'), (7, 'Key4 - Consejo Judicatura')], default=3, verbose_name='Token para firmar')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('mobile', models.CharField(max_length=10, verbose_name='Celular')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('web', models.URLField(blank=True, max_length=60, verbose_name='Página web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidad Emisor',
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.CharField(max_length=2, verbose_name='Código')),
                ('detail', models.CharField(max_length=60, verbose_name='Detalle')),
                ('ceated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Código')),
                ('detail', models.CharField(max_length=60, verbose_name='Detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='KeyConformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(max_length=8, verbose_name='Fecha de Emisión')),
                ('TYPE_OF_ENVIRONMENT', models.IntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCION')], default=1, verbose_name='Tipo de Ambiente')),
                ('series', models.CharField(max_length=6, verbose_name='Serie')),
                ('voucher_number', models.CharField(max_length=9, verbose_name='Número de comprobante')),
                ('numeric_code', models.BigIntegerField(verbose_name='Código Numérico')),
                ('check_digit', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('ruc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Company', verbose_name='Ruc')),
                ('type_of_emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Emission', verbose_name='tipo de Emisión')),
            ],
            options={
                'verbose_name': 'Conformación clave',
                'verbose_name_plural': 'Conformación clave',
            },
        ),
        migrations.CreateModel(
            name='Measurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('detail', models.CharField(max_length=254, verbose_name='Detalle')),
                ('model', models.CharField(max_length=30, verbose_name='Modelo')),
                ('initial_reading', models.IntegerField(verbose_name='Lectura inicial')),
                ('state', models.NullBooleanField(verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_voucher_status', models.CharField(max_length=60, verbose_name='Estado del comprobante electróncio')),
                ('acronym', models.CharField(max_length=3, verbose_name='siglas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=13, unique=True, verbose_name='Cédula / Ruc')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellido')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('address', models.CharField(max_length=254, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('mobile', models.CharField(max_length=15, verbose_name='Celular')),
                ('state', models.NullBooleanField(verbose_name='estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Measurer')),
            ],
            options={
                'verbose_name': 'Abonado',
                'verbose_name_plural': 'Abonados',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13, verbose_name='Número')),
                ('business_name', models.CharField(max_length=100, verbose_name='Razón social')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Identification', verbose_name='Identificación')),
            ],
        ),
        migrations.CreateModel(
            name='TypeVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Código')),
                ('detail', models.CharField(max_length=60, verbose_name='detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
        ),
        migrations.AddField(
            model_name='keyconformation',
            name='type_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.TypeVoucher', verbose_name='tipo de comprobante'),
        ),
    ]
