# Generated by Django 2.1.5 on 2019-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimieno'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='configuration/subscribers/', verbose_name='Retrato'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
    ]
