# Generated by Django 2.1.5 on 2019-03-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20190320_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='base_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='basic_rate',
        ),
        migrations.AddField(
            model_name='typesservice',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base'),
        ),
        migrations.AddField(
            model_name='typesservice',
            name='limit',
            field=models.IntegerField(default=11, verbose_name='Rango Superior'),
        ),
    ]
