# Generated by Django 2.1.5 on 2019-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20190320_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='exceeding_rate',
            new_name='excess_rate',
        ),
        migrations.AddField(
            model_name='typesservice',
            name='excess_rate_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Valor por excedente'),
        ),
    ]
