# Generated by Django 2.1.5 on 2019-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20190320_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesservice',
            name='excess_rate_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base excedente'),
        ),
    ]
