# Generated by Django 2.1.5 on 2019-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20190321_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='Detalle de la multa o sanción')),
                ('sanction', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Económico')),
                ('state', models.BooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Multa y Sanción',
                'verbose_name_plural': 'Multas y Sanciones',
                'ordering': ['detail'],
            },
        ),
        migrations.AlterField(
            model_name='rate',
            name='lowre_range',
            field=models.IntegerField(default=0, verbose_name='Rango Inicial'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='top_range',
            field=models.IntegerField(default=0, verbose_name='Rango Superior'),
        ),
    ]
