# Generated by Django 2.1.5 on 2019-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_auto_20190327_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='state',
            field=models.NullBooleanField(verbose_name='Activo'),
        ),
    ]
