# Generated by Django 2.1.5 on 2019-03-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20190327_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesservice',
            name='maximum_consumption',
            field=models.IntegerField(default=0, verbose_name='Consumo máximo'),
        ),
        migrations.AddField(
            model_name='typesservice',
            name='state_maximum_consumption',
            field=models.NullBooleanField(verbose_name='Tiene limite de consumo máximo'),
        ),
    ]
