# Generated by Django 2.1.5 on 2019-03-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_auto_20190327_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesservice',
            name='maximum_consumption_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor por consumo máximo'),
        ),
    ]
