# Generated by Django 2.1.5 on 2019-03-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_typesservice_maximum_consumption_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='Tipo de Descuento')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('state', models.NullBooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={'ordering': ['id'], 'verbose_name': 'Multa y Sanción', 'verbose_name_plural': 'Multas y Sanciones'},
        ),
        migrations.AlterModelOptions(
            name='measurer',
            options={'ordering': ['id'], 'verbose_name': 'Medidor', 'verbose_name_plural': 'Medidores'},
        ),
    ]
