# Generated by Django 2.1.5 on 2019-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_auto_20190327_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='Tipo de Descuento')),
                ('state', models.NullBooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pagos',
            },
        ),
    ]
