# Generated by Django 2.1.5 on 2019-03-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_paymentmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='measurer',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Measurer',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
