# Generated by Django 2.1.5 on 2019-03-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='Detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['detail'],
            },
        ),
        migrations.CreateModel(
            name='Measurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('detail', models.CharField(max_length=254, verbose_name='Detalle')),
                ('model', models.CharField(max_length=30, verbose_name='Modelo')),
                ('initial_reading', models.IntegerField(verbose_name='Lectura inicial')),
                ('state', models.NullBooleanField(verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=13, unique=True, verbose_name='Cédula / Ruc')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellido')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('address', models.CharField(max_length=254, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('state', models.NullBooleanField(verbose_name='estado')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimieno')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='configuration/subscribers/', verbose_name='Retrato')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Measurer')),
            ],
            options={
                'verbose_name': 'Abonado',
                'verbose_name_plural': 'Abonados',
                'ordering': ['surname'],
            },
        ),
    ]
