# Generated by Django 2.1.5 on 2019-03-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='measurer',
        ),
    ]
