# Generated by Django 2.1.5 on 2019-04-02 14:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_auto_20190328_1115'),
        ('cadastre', '0002_remove_subscribers_measurer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastre_number', models.IntegerField(unique=True, verbose_name='Numero catastral')),
                ('date_admission', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalle')),
                ('state', models.NullBooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha admisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Discount', verbose_name='Tipo descuento')),
                ('measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Measurer', verbose_name='Medidor')),
                ('payment_methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.PaymentMethods', verbose_name='Forma de Pago')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Rate', verbose_name='Tarifa')),
                ('subscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Subscribers', verbose_name='Abonado')),
            ],
            options={
                'verbose_name': 'Planilla catastral',
                'verbose_name_plural': 'Planillas Catastrales',
                'ordering': ['id'],
            },
        ),
    ]
