# Generated by Django 2.1.5 on 2019-04-03 01:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_auto_20190328_1115'),
        ('cadastre', '0003_cadastral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_period', models.DateField(unique=True, verbose_name='Período consumo')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='Detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha emisión')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
            },
        ),
        migrations.CreateModel(
            name='ReadingsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reading', models.PositiveIntegerField(verbose_name='Lectura actual')),
                ('previous_reading', models.PositiveIntegerField(verbose_name='Lectura anterior')),
                ('reading_type', models.IntegerField(choices=[(1, 'Real'), (2, 'Estimado')], default=1, verbose_name='M. cálculo')),
                ('consumption', models.PositiveIntegerField(verbose_name='Consumo M3')),
                ('diameter', models.CharField(max_length=5, verbose_name='iámetro')),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Cadastral', verbose_name='Clave catastral')),
                ('fines', models.ManyToManyField(default=1, to='configuration.Fines', verbose_name='Otros valores por pagar')),
                ('readings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastre.Readings', verbose_name='Lecturas')),
            ],
            options={
                'verbose_name': 'Detalle Lectura',
                'verbose_name_plural': 'Detalle Lecturas',
            },
        ),
    ]
