from django.contrib import admin
from django.urls import path
from .views import (
    CompanyListView,
    CompanyDetailView,
    CompanyCreateView,
    CompanyUpdateView,
    CompanyDeleteView,
    TypesServiceListView,
    TypesServiceDetailView,
    TypesServiceCreateView,
    TypesServiceUpdateView,
    TypesServiceDeleteView,
    RateListView,
    RateDetailView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    FinesListView,
    FinesDetailView,
    FinesCreateView,
    FinesUpdateView,
    FinesDeleteView,
    DiscountListView,
    DiscountDetailView,
    DiscountCreateView,
    DiscountUpdateView,
    DiscountDeleteView,
    PaymentMethodsListView,
    PaymentMethodsDetailView,
    PaymentMethodsCreateView,
    PaymentMethodsUpdateView,
    PaymentMethodsDeleteView,

    )



configuration_patterns = ([
    path('company_list/', CompanyListView.as_view(), name="company_list"),
    path('company_detail/<int:pk>/', CompanyDetailView.as_view(), name="company_detail"),
    path('company_create/', CompanyCreateView.as_view(), name="company_create"),
    path('company_update/<int:pk>/', CompanyUpdateView.as_view(), name="company_update"),
    path('company_delete/<int:pk>/', CompanyDeleteView.as_view(), name="company_delete"),
    path('typesservice_list', TypesServiceListView.as_view(), name='typesservice_list'),
    path('typesservice_detail/<int:pk>/', TypesServiceDetailView.as_view(), name='typesservice_detail'),
    path('typesservice_create/', TypesServiceCreateView.as_view(), name="typesservice_create"),
    path('typesservice_update/<int:pk>/', TypesServiceUpdateView.as_view(), name="typesservice_update"),
    path('typesservice_delete/<int:pk>/', TypesServiceDeleteView.as_view(), name="typesservice_delete"),
    path('rate_list', RateListView.as_view(), name='rate_list'),
    path('rate_detail/<int:pk>/', RateDetailView.as_view(), name='rate_detail'),
    path('rate_create/', RateCreateView.as_view(), name="rate_create"),
    path('rate_update/<int:pk>/', RateUpdateView.as_view(), name="rate_update"),
    path('rate_delete/<int:pk>/', RateDeleteView.as_view(), name="rate_delete"),
    path('fines_list', FinesListView.as_view(), name='fines_list'),
    path('fines_detail/<int:pk>/', FinesDetailView.as_view(), name='fines_detail'),
    path('fines_create/', FinesCreateView.as_view(), name="fines_create"),
    path('fines_update/<int:pk>/', FinesUpdateView.as_view(), name="fines_update"),
    path('fines_delete/<int:pk>/', FinesDeleteView.as_view(), name="fines_delete"),
    path('discount_list', DiscountListView.as_view(), name='discount_list'),
    path('discount_detail/<int:pk>/', DiscountDetailView.as_view(), name='discount_detail'),
    path('discount_create/', DiscountCreateView.as_view(), name="discount_create"),
    path('discount_update/<int:pk>/', DiscountUpdateView.as_view(), name="discount_update"),
    path('discount_delete/<int:pk>/', DiscountDeleteView.as_view(), name="discount_delete"),
    path('paymentmethods_list', PaymentMethodsListView.as_view(), name='paymentmethods_list'),
    path('paymentmethods_detail/<int:pk>/', PaymentMethodsDetailView.as_view(), name='paymentmethods_detail'),
    path('paymentmethods_create/', PaymentMethodsCreateView.as_view(), name="paymentmethods_create"),
    path('paymentmethods_update/<int:pk>/', PaymentMethodsUpdateView.as_view(), name="paymentmethods_update"),
    path('paymentmethods_delete/<int:pk>/', PaymentMethodsDeleteView.as_view(), name="paymentmethods_delete"),

],'ajustes')
